spring:
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true # data.sql? ???? ?? ??
    show-sql: true # console?? SQL? ??? ? ??
    properties:
      hibernate:
        format_sql: true # ??? ?? ?? ????